kind: pipeline
type: docker
name: deploy-flow-api

steps:
  - name: test-runner
    image: arm64v8/alpine
    commands:
      - uname -m
      - echo "âœ… Runner ARM64 funcionando"

  - name: build-image
    image: moby/buildkit:latest
    environment:
      REGION: us-west1
      PROJECT_ID: manifest-grin-462423-m3
      REPO_NAME: hackaton
      SERVICE_NAME: flow-api
      LOCAL_IMAGE: bloodbloy/flow-api
      REMOTE_IMAGE: us-west1-docker.pkg.dev/manifest-grin-462423-m3/hackaton/flow-api:latest
    commands:
      - echo "ðŸ”¨ Building Docker image..."
      - buildctl build \
          --frontend dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=docker,name=$REMOTE_IMAGE \
          --opt platform=linux/amd64 \
          --no-cache

  - name: tag-and-push
    image: docker.io/arm64v8/docker
    environment:
      LOCAL_IMAGE: bloodbloy/flow-api
      REMOTE_IMAGE: us-west1-docker.pkg.dev/manifest-grin-462423-m3/hackaton/flow-api:latest
    commands:
      - echo "ðŸ·ï¸ Tagging and pushing image..."
      - docker tag $LOCAL_IMAGE $REMOTE_IMAGE
      - docker push $REMOTE_IMAGE

  - name: write-env-file
    image: arm64v8/alpine
    environment:
      ENV_FILE_CONTENT:
        from_secret: cloudrun_env_yaml
    commands:
      - echo "$ENV_FILE_CONTENT" > .env.yaml

  - name: deploy-cloud-run
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    environment:
      PROJECT_ID: manifest-grin-462423-m3
      REGION: us-west1
      SERVICE_NAME: flow-api
      REMOTE_IMAGE: us-west1-docker.pkg.dev/manifest-grin-462423-m3/hackaton/flow-api:latest
      GCLOUD_SERVICE_KEY:
        from_secret: gcloud_service_key
    commands:
      - echo "ðŸ”‘ Authenticating with GCP..."
      - echo "$GCLOUD_SERVICE_KEY" > /tmp/key.json
      - gcloud auth activate-service-account --key-file=/tmp/key.json
      - gcloud config set project $PROJECT_ID
      - echo "ðŸš€ Deploying to Cloud Run..."
      - gcloud run deploy $SERVICE_NAME \
          --image $REMOTE_IMAGE \
          --region $REGION \
          --allow-unauthenticated \
          --env-vars-file .env.yaml \
          --memory 2Gi \
          --cpu 2 \
          --project $PROJECT_ID

trigger:
  branch:
    - main
    - master
