when:
  - branch: main
    event: push



steps:
  build:
    image: plugins/docker
    settings:
      registry: us-west1-docker.pkg.dev
      repo: us-west1-docker.pkg.dev/manifest-grin-462423-m3/hackaton/flow-api
      tags: latest
      username: _json_key
      password:
        from_secret: gcloud
      dockerfile: Dockerfile
      context: .
      platforms: linux/amd64

  deploy:
    image: alpine:3.20
    environment:
      GCP_SERVICE_ACCOUNT_KEY:
        from_secret: gcloud
      ENV_FILE_CONTENT:
        from_secret: env_yaml
      REGION: 
        from_secret: region
      PROJECT_ID:
        from_secret: project_id
      REPO_NAME: 
        from_secret: repo_name
      SERVICE_NAME: 
        from_secret: service_name
    commands:
      - apk add --no-cache curl bash python3 py3-pip
      - curl -sSL https://sdk.cloud.google.com | bash
      - export PATH="$HOME/google-cloud-sdk/bin:$PATH"
      - echo "$${GCP_SERVICE_ACCOUNT_KEY}" > /tmp/gcp-key.json
      - echo "$${ENV_FILE_CONTENT}" > .env.yaml
      - gcloud auth activate-service-account --key-file /tmp/gcp-key.json
      - gcloud config set project $${PROJECT_ID}
      - echo "🚀 Deploying to Cloud Run..."
      - gcloud run deploy $${SERVICE_NAME} --image $${REGION}-docker.pkg.dev/$${PROJECT_ID}/$${REPO_NAME}/$${SERVICE_NAME}:latest --region $${REGION} --allow-unauthenticated --env-vars-file .env.yaml --memory 2Gi --cpu 2 --project $${PROJECT_ID}
    depends_on:
      - build
